spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-static-route
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/products/**
            - id: payment-service-static-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/payments/**

server:
  port: 8888

