services:
  config-server:
    image: halitkalayci/turkcell-45-config-server
    ports:
      - "8989:8989"
  discovery-server:
    image: halitkalayci/tcell-45-discovery-server
    ports:
      - "8761:8761"
  gateway-server:
    image: halitkalayci/tcell-45-gateway-server
    ports:
      - "8888:8888"
    depends_on:
      - config-server
    environment:
      - CONFIG_URI=http://config-server:8989

# Bütün servisleri docker image haline getirelim
# docker composeda hepsini temsil edecek servisleri yazalım hepsini dockerda ayağa kaldırabiliyor olalım.